cloudflare-api-token: ENC[AES256_GCM,data:zSzOW/SHV7NMhx9mhA2xz2znvZK3/cPyWyJH/mmm6FM146N5SdqzYaL/UujyJ0flybvAh5lrmeLa7bR28Wf7Pa4s5wD1Nw==,iv:16tcNSfhHrvm1JYzOhWJIgc8DK36XNc8FMqEPMt/iJg=,tag:6EGwqa4dnHTTuCwpLCXvtw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QXkyWEZ4YzlVZE5rOS9P
        YXJSM0xYa1c0b2NIN2xvUW12UzlmSkkwRUhJCmsvRGhtWlFmTmljWFM5cmNNV1E1
        Q3RiQ0l6bTZhVXpOY3Z6V2sxS2VjaWMKLS0tIFIyTERRbHBRMUlSSWhZdWJqaDli
        NGZ3Ym1CUzdXNjRiTTlEaHlxUnVlQ00K2rm6qu9gaqOtwkLn8QlMzYxUhcur/ibG
        kKpl8BF8PhgC0p3ayx9YbwX/Zv32hljiESpgbA403CrIcpjxNWWMgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahvwx3a7z6df3avdy6w9y3a4ggqvv80s3thqu4dlqj76822ct36qh23jle
  lastmodified: '2026-05-26T22:17:12Z'
  mac: ENC[AES256_GCM,data:/aWmJwEonRWRS0ehNqRI2g2OAmSyF8Gotz2KWhV2wfM1ciT23XuXtXoeUPX5s/rtQwe5M+jTXHb4aZEmp6wZhOLBY5HDxebmV2jKRb+GkNMWKeZqMkHmpw8pS/+AkgBSdCEOuoEGZhEaSY64iaC7GbtAHxLoru2edjBB22WSjOk=,iv:FXtIXAQFPUInDnCeGuDnNweZ9J/5F0kYK1VyDT5+UYg=,tag:Fg1Sajf2M3YIb/sebIPiIQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
