keys:
  # UM790-Pro: ssh-to-age で取得した age public key を貼り付け
  # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
  - &um790pro age1_PLACEHOLDER_RUN_SSH_TO_AGE_ON_UM790PRO
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *um790pro
