# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aqua = {
    pname = "aqua";
    version = "v2.55.3";
    src = fetchFromGitHub {
      owner = "aquaproj";
      repo = "aqua";
      rev = "v2.55.3";
      fetchSubmodules = false;
      sha256 = "sha256-7m7lDMUeN4m3yUMelwVZyC+cWhwD20/FUbbb7YfNWfw=";
    };
    vendorHash = "sha256-YdbHccVVWJ/1eVzTaXSV+PeDQNiZhOnJGd+dtOtmKac=";
  };
  difit = {
    pname = "difit";
    version = "v3.0.2";
    src = fetchFromGitHub {
      owner = "yoshiko-pg";
      repo = "difit";
      rev = "v3.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-EFoDA8KN/3giLzz39v7Rsr1in6gVilsI5vrPNgAI1d4=";
    };
    pnpmDepsHash = "sha256-JDp3mBDV0cPK5445nRJqLn/uFhfl3P4unO42tqzTUmY=";
  };
  entire = {
    pname = "entire";
    version = "v0.4.4";
    src = fetchFromGitHub {
      owner = "entireio";
      repo = "cli";
      rev = "v0.4.4";
      fetchSubmodules = false;
      sha256 = "sha256-6/TsSmJ0z72Ta5ZihO06uV4Mik+fFpm8eCa7d5zlq24=";
    };
    vendorHash = "sha256-rh2VhdwNT5XJYCVjj8tnoY7cacEhc/kcxi0NHYFPYO8=";
  };
  jj-desc = {
    pname = "jj-desc";
    version = "v0.4.3";
    src = fetchFromGitHub {
      owner = "tumf";
      repo = "jj-desc";
      rev = "v0.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-ptenxz97I17xgfSzDKrF/ieOCe7u25i1bZz45nsPExw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-ptenxz97I17xgfSzDKrF_ieOCe7u25i1bZz45nsPExw=/Cargo.lock";
      outputHashes = {

      };
    };
  };
  keifu = {
    pname = "keifu";
    version = "v0.2.3";
    src = fetchFromGitHub {
      owner = "trasta298";
      repo = "keifu";
      rev = "v0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-8fjR204Wa9LJa9JGQ1CRHDoiHei6P3J81RGgA0G77EA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-8fjR204Wa9LJa9JGQ1CRHDoiHei6P3J81RGgA0G77EA=/Cargo.lock";
      outputHashes = {

      };
    };
  };
  polycat = {
    pname = "polycat";
    version = "f81e73bbb5de90a496bb0b844cdb3a93e54fbaad";
    src = fetchFromGitHub {
      owner = "2IMT";
      repo = "polycat";
      rev = "f81e73bbb5de90a496bb0b844cdb3a93e54fbaad";
      fetchSubmodules = false;
      sha256 = "sha256-wpDx6hmZe/dLv+F+kbo+YUIZ2A8XgnrZP0amkz6I5IQ=";
    };
    date = "2025-05-23";
  };
  pretty-ts-errors-markdown = {
    pname = "pretty-ts-errors-markdown";
    version = "4d4a167d4cc9bd6c07945c89441b154746e2b2d6";
    src = fetchFromGitHub {
      owner = "hexh250786313";
      repo = "pretty-ts-errors-markdown";
      rev = "4d4a167d4cc9bd6c07945c89441b154746e2b2d6";
      fetchSubmodules = false;
      sha256 = "sha256-zxp8YAfF15sE8EZmO3IFB7PmJAw9GfGhGlJQs0qliz4=";
    };
    npmDepsHash = "sha256-aC+t2FYWJgDzXmfYg2IDJ7W2pLPAZ1o3TC68MWZhbSg=";
    date = "2025-04-24";
  };
  similarity-ts = {
    pname = "similarity-ts";
    version = "v0.4.2";
    src = fetchFromGitHub {
      owner = "mizchi";
      repo = "similarity";
      rev = "v0.4.2";
      fetchSubmodules = false;
      sha256 = "sha256-/rvLl2SaeB0AHEbjkT/XTvVZHHoRaau44SteImRWguE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-_rvLl2SaeB0AHEbjkT_XTvVZHHoRaau44SteImRWguE=/Cargo.lock";
      outputHashes = {

      };
    };
  };
}
