nextcloud-admin-pass: ENC[AES256_GCM,data:2M6QMTAS4zJrQtcw+io3J4gIeKiVardeP4fzUitAJjvEadcru0VpXHN0Zfw=,iv:RnAXxQE/z9/P6x5QI3f8VRHUjzvVGyn7rK+W5vFIsKw=,tag:xGXRkp9oqKOrbFY2W6A2IA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWTNkV2s2ZkdReHBTV2pL
        ZnpxTFAyUWVKbXhJM01LUDh5QWZkZ042VmpZClA2WnY0Zm9hV3F4UnpXYkJqaUN1
        OVVHZjN5UHFma3RLUUcwV25FcURocnMKLS0tIHdObXZBcmtHYk1ZanRoR1RxeWpO
        OU1EemoydHRhVjlVUDZKRDNtTWdya3MK4xdDNHAE6OH1uLa4zMXWSVDGNWQfzIgO
        A5DordfTqGXpwhPkTch1iTHdPPAPvM9Q7URmOjapHuqlIXdZTB6d2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahvwx3a7z6df3avdy6w9y3a4ggqvv80s3thqu4dlqj76822ct36qh23jle
  lastmodified: '2026-05-25T10:32:03Z'
  mac: ENC[AES256_GCM,data:rHLNBMomsoMMMLfFc9ASC+JNl75ZENRvt+I0pYqQJ19VqLesTSttxftd39M4jhugLUrwI6JaYFV/ulQG5q9XeqF7pBl9Xcfm4oihK7Wc+7qCDjRTGLIRfgoeEnR86CbfrdOqWAGzRrYCmcpP2d8/lFAWEink7Nnt1IO2SaLAZsQ=,iv:tV9a96K2rIH4npimkzOgRmkAC/mQ2Z3/xN8CX3Y4RU4=,tag:J94MiXD3T24Gi+bt+nWckQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
