{
  config,
  lib,
  ...
}:

let
  cfg = config.my.services.newsyslog;

  mkFlagString =
    flags:
    let
      result = lib.concatStrings (lib.sort lib.lessThan flags);
    in
    if result == "" then "-" else result;

  mkEntryLine =
    name: entry:
    let
      logfile = if entry.logfile != null then entry.logfile else name;
      ownerGroup =
        if entry.owner != null || entry.group != null then
          "${lib.optionalString (entry.owner != null) entry.owner}:${
            lib.optionalString (entry.group != null) entry.group
          }"
        else
          "";
      sizeStr = if entry.size == "*" then "*" else toString entry.size;
      flagStr = mkFlagString entry.flags;
      pidPart = lib.optionalString (entry.pidFile != null) "\t${entry.pidFile}";
      signalPart = lib.optionalString (entry.signal != null) "\t${toString entry.signal}";
    in
    "${logfile}\t${ownerGroup}\t${entry.mode}\t${toString entry.count}\t${sizeStr}\t${entry.when}\t${flagStr}${pidPart}${signalPart}";

  entryModule = lib.types.submodule (
    { name, ... }:
    {
      options = {
        enable = lib.mkEnableOption "this newsyslog entry" // {
          default = true;
        };
        logfile = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          description = "Log file path. Defaults to the attribute name.";
        };
        owner = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
        };
        group = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
        };
        mode = lib.mkOption {
          type = lib.types.strMatching "[0-7]{3,4}";
          default = "644";
        };
        count = lib.mkOption {
          type = lib.types.ints.unsigned;
          default = 5;
        };
        size = lib.mkOption {
          type = lib.types.either (lib.types.enum [ "*" ]) lib.types.ints.positive;
          default = "*";
        };
        when = lib.mkOption {
          type = lib.types.str;
          default = "*";
        };
        flags = lib.mkOption {
          type = lib.types.listOf (
            lib.types.enum [
              "B"
              "C"
              "D"
              "G"
              "J"
              "N"
              "Z"
            ]
          );
          default = [ ];
        };
        pidFile = lib.mkOption {
          type = lib.types.nullOr lib.types.path;
          default = null;
        };
        signal = lib.mkOption {
          type = lib.types.nullOr lib.types.ints.positive;
          default = null;
        };
      };
    }
  );

  enabledEntries = lib.filterAttrs (_: entry: entry.enable) cfg.settings;
  configLines = lib.mapAttrsToList mkEntryLine enabledEntries;
in
{
  options.my.services.newsyslog = {
    enable = lib.mkEnableOption "newsyslog log rotation configuration";
    settings = lib.mkOption {
      type = lib.types.attrsOf entryModule;
      default = { };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = lib.flatten (
      lib.mapAttrsToList (name: entry: [
        {
          assertion = !(lib.elem "J" entry.flags && lib.elem "Z" entry.flags);
          message = "newsyslog entry '${name}': cannot use both J and Z compression";
        }
        {
          assertion = entry.signal == null || entry.pidFile != null;
          message = "newsyslog entry '${name}': signal requires pidFile to be set";
        }
      ]) cfg.settings
    );

    environment.etc."newsyslog.d/nix-darwin.conf".text = ''
      # Generated by nix-darwin
      # logfilename          [owner:group]    mode count size  when  flags [/pid_file] [sig_num]
      ${lib.concatStringsSep "\n" configLines}
    '';
  };
}
