(set vim.g.mapleader " ")
(set vim.g.maplocalleader " ")

(set vim.opt.number true)
(set vim.opt.relativenumber true)
(set vim.opt.termguicolors true)
(set vim.opt.signcolumn "yes")
(set vim.opt.wrap false)
(set vim.opt.undofile true)
(set vim.opt.ignorecase true)
(set vim.opt.smartcase true)
(set vim.opt.updatetime 250)
(set vim.opt.timeoutlen 300)
(set vim.opt.splitright true)
(set vim.opt.splitbelow true)
(set vim.opt.scrolloff 8)
