grafana-secret-key: ENC[AES256_GCM,data:ECJewtcfSoEkuid5Ng/XyHQyLFS20ISgO7V5nIjImnIKtjqBfgf5cxhQQcJLf2+dYzTHKw4eDTAyPmKWIM2a4hjnkZBMitlaD6KpPlPi5MMIlxtDjLNSyxQ=,iv:0xOam7x9PG09k0NoQR3wamMDzogp+b/fV7RNM+ZIYmo=,tag:G9hLz74RD7PSYyt803XZRQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYTBaQXUwb2xoVnQxc2l6
        YXE2Z1dIS3loU1BlY1kwNUx5WFl1ZFFXREg4ClZKQU1xaFUyOSsxSE4vZ1V1VFkv
        MlFSZUJLdEpLaFF0eHRmY1I3N3FESDQKLS0tIElNNFNFcWpuSFZSUEFVQmpmTS9V
        VjBJOW9NQWllZ2kyWTRUSWE5Z01TaVUKGfSpCtq6ZnDvlUh0yPNH6zczEunLivqY
        472r1yguuswv0xw3Ywk8Ke/L0/LypNHe8CadnSJeqHO4RO+sHn5hgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahvwx3a7z6df3avdy6w9y3a4ggqvv80s3thqu4dlqj76822ct36qh23jle
  lastmodified: '2026-05-25T10:32:03Z'
  mac: ENC[AES256_GCM,data:GyqGWjQtjRrIceCjLjKlAz0w3uVyoAGJRkPbbtzP5gyYwUixpTcyCzReSYQj1o1hIONi5hwiQ+29kn54K5UUpfgfSmHmztb+lauvmCLL7S+mcsHNaKpC7j+N2kUOiZuNXVnovS57bw/zNYjEHVrDift+vYOBBEyFbsuuJ+smZS8=,iv:7YgJX4v1LdWyXbdoIH1QKa3xHMvyNn61Y7/GIizyHV8=,tag:XIjqoSc1XVgqnGdm1hmSvQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
