name: Setup Git Bot
description: Generate GitHub App token and configure git identity

inputs:
  app-id:
    description: GitHub App ID
    required: true
  app-private-key:
    description: GitHub App private key
    required: true

outputs:
  token:
    description: GitHub App installation token
    value: ${{ steps.token.outputs.token }}

runs:
  using: composite
  steps:
    - id: token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-private-key }}

    - shell: bash
      env:
        GH_TOKEN: ${{ steps.token.outputs.token }}
        APP_SLUG: ${{ steps.token.outputs.app-slug }}
      run: |
        BOT_ID=$(gh api "users/${APP_SLUG}[bot]" --jq '.id')
        git config user.name "${APP_SLUG}[bot]"
        git config user.email "${BOT_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
