#!/usr/bin/env zsh

# Lean, two-line prompt: pastel text and icons on the terminal's own background.
typeset -g POWERLEVEL9K_MODE=nerdfont-v3
typeset -g POWERLEVEL9K_ICON_PADDING=moderate
typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true
typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=
typeset -g POWERLEVEL9K_MULTILINE_{FIRST,NEWLINE,LAST}_PROMPT_PREFIX=
typeset -g POWERLEVEL9K_MULTILINE_{FIRST,NEWLINE,LAST}_PROMPT_SUFFIX=
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

typeset -ga POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon dir vcs
  newline prompt_char
)
typeset -ga POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status command_execution_time background_jobs
  direnv nix_shell virtualenv node_version rust_version context
  newline
)

typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#89b4fa'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#b4befe'
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#9399b2'
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER='…'
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true

typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_BACKGROUND=
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#fab387'
typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND='#9399b2'
typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#f5c2e7'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

# Only show status on failure, duration for slower commands, and active environments.
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR=true
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#f5c2e7'
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND='#fab387'
typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION=
typeset -g POWERLEVEL9K_CONTEXT_SUDO_CONTENT_EXPANSION=

typeset -g POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
