# Thanks: https://github.com/ryoppippi/dotfiles/blob/main/.github/actions/setup-nix/action.yaml
name: Setup Nix
description: Install Nix and configure caches

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      with:
        github_access_token: ${{ github.token }}
    - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: numtide
        skipPush: true
    - name: Setup niks3
      uses: Mic92/niks3-action@bc010bf9dbc79ec59de6c79b1e7a167977d3978b # v1.0.0
      with:
        server-url: https://niks3.yutakobayashi.com
