name: Setup Nix
description: Install Nix and configure numtide cache

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: numtide
        skipPush: true
