tailscale-authkey: ENC[AES256_GCM,data:A8m0WgFi/t2DXSgHGTufmrA917hj2l2xJJVidLtXM2wlpUjPwXypFjnQmmaKGs2Yusx4Ih5b2aXPelHt/MI=,iv:ZBamStOEjz9FeH7fqC/MTHFweNcWg5K2LYNSmeH56Vs=,tag:qqj8rEk6i52VoM6lzrRATQ==,type:str]
wifi: ENC[AES256_GCM,data:fC758yejk08LE632sNpQlJRanS2Xurxc2MffJWf9wej7OfPB1QTFE36stGOwGG08X37Avy5ErqrahoysTuAsjFKSzDVhOQ==,iv:zQgfMcCqNigI044xH/HykkC1Vl3ANz6AeDeHtprBj2k=,tag:H9h/ZYwYTVrGqKWFs+vLnw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWjJ5Rk9ESERWZ1BRREwx
        NjJJUHRFaUhweCswWEhXYjdINnFSS1JxOFZvCkkzVVREeXVHL09XbjJtNG1PTXhn
        SDN4U0N1ZlNKNzBwUytqZlZPTWl5eVEKLS0tIFZ5Y25XcytlQXVCcW0yVU5XeTdx
        aGFOMmEwZnJPYTg0NExnNFNPb3g2Y2sK9DNZPVWpvRelTxN67NAm3FbkuZ+s7d01
        6On64PTt6HLO8qYsFJYK1Qtug5Hu5EbvIaAGv0Y6pUpcZyuLJyR9bw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u8ah2hga53uh7y24efhuc5vszzctqxth2rtvd7dshedpl9l50d5slzs6zq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZjQra1hGcDMxN0dSak95
        WDNyR0JGZ1RISDlpajZocFVYYXN6UU9xZFdrCktldzJsU0lQbU9lY1pGQWpFU0RZ
        TkhTR3RHSGtxamVzYU1rRkZvVHBMSjAKLS0tIEtZWWdDQWNJNGxiVUtNb2l5OHd0
        OHovK0RGSnc1Rk9saE9SNFVIRjlDMzQKs1DliaGMRMNy0QwWKQUOHeCvoDrTq3zF
        DOPAS7a9ms2lU4SA7hMChyx/LyKpg3GZU9ovVFG/u5jHFyeftxG+/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahvwx3a7z6df3avdy6w9y3a4ggqvv80s3thqu4dlqj76822ct36qh23jle
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNmNDT2IvYUtvSmJaR1RE
        TU5MZitkT0xOTUZmRXFtalFLQTRsR3VKTENNCm5XNUJ6ZDQ1WTZ2am1xTldSbUhD
        NW1qckx3ZHVXT3RLa29JWW9xWXYvOTAKLS0tIC84OUxRN0VLTlpBVVVKNTVYWldF
        SjU5N3FuZ1NFVm5GKzJZaGladDFkWUEKkU/7sFTjcW5STBxLIISaRXAFma3IswYO
        2PIfWofIYapFtyrB9Rzko5kTxdgYHa319aYog8e5DAbJswa5sSgXLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a5cyt62c4ejr28d307x6prc2vrzvhugvelu7eq8vcs0gjmrjvuwq5vnd88
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ254bVh2SGNRb2Z4eHRl
        ck9jVlpITVVkR0RzMHN0YWpCYXc4VkdPd21vCm9OOWNwWDdXVmdQVzBjVk81Vjli
        dStzd0ZBYWRZdWFzQkFSY2pKaEFxZG8KLS0tIHdFYU82bjlMWXVpQ3JOc1VkOE5N
        Rm90bDY2a0ZzcmtRbHF0U2VKUU96TjgKAP4QuZQyh62ultI2GOJMCTphYAxcjby9
        ilO+uXmomwoo/L0S45+Y3PuPDxPywVtFj0KqeUPL7PIQ73jyPg5OCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g96vx3ghxfge06xkxrfcfwq607p4fp75xcg6efgz9mf87l2a7u5qk04rfw
  lastmodified: '2026-05-17T07:29:58Z'
  mac: ENC[AES256_GCM,data:UgMcgakBjxGICZrJBRqiN1oqfZZF+1fntFU0Q3GtCzTcxwpScBRwNvF8w4BvPQsGoWQWRjgaMCqKHgbWQlxCkaJzBHMNDC8RBF/4HRKjenN48UcT57sPLf+t+6rvd8gNUZEczBU/2FZT4I46MvmiqlMy0cj0kqJFJVB3+ZVaOlU=,iv:m/2VncMdlYVUPAd4lgJWSUDKSVfRpNChrH7e8IuxWzs=,tag:icWU+weHh9TxBs6KkGz2Uw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.0
