tailscale-authkey: ENC[AES256_GCM,data:JgoGCIEZxTExLYthPWBCNyIFxrmcElFJzcdkbSLQeRvmr+l2dHkLo7KF/dYgiD7MtzDVTdLjOVOH3rLWGQ==,iv:XO/nZn4qX1NOzHJtf3x88p7/4nMGIhNvCatrpxNa3es=,tag:1sVkg+VDf+5Y4AFxHtPjpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL0VYbjlzZTB4NzJsallh
        SW4yZmtWTXpQMEE0NHhnSDhvYmFjcTBEdXhzCnVWTmtoM0FMWWJuQTcwSnVQVkt4
        TTUrOFBOTWlZRjBHdnJxb2lXK0FBY0kKLS0tIFRQb3ZwTk11ZmZvN0xHMFhvMDNI
        alhERHk2NGloWWtUalNNcnVNWE04TzQKI4OiuSRmBBR1FRdsm+qDjjAT1E3NK3ND
        yV9TBDZ6o5xqkkc+H4+zacAYyaW7UfUgPUw+HbQoYQv6s9ibunULyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u8ah2hga53uh7y24efhuc5vszzctqxth2rtvd7dshedpl9l50d5slzs6zq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U2NzalRCS3k3cGpiaTBJ
        TDl1OENrREN5ZDJBMGJTbGs5MEk2SUVwSVRnCmg1WTBUczNaNzBJdjl0L0Y1YWFp
        RzBzUHpsZUZ5bHpIVjJJWExlVmdoRjgKLS0tIEtKNTRlOGlBWnRxckMycWFvdVNa
        ejBrQUlZVVRoekVkMGl1a1BOS01IWlEK+eQeo/vOxpjt44zaZictZFFpE0NS5m4q
        iwmF9gwXT0uFtgVyKmJaJdWOTqkjwCzj+CU4wFFc2v743yk8GRu6xw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahvwx3a7z6df3avdy6w9y3a4ggqvv80s3thqu4dlqj76822ct36qh23jle
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcEUxRkVsaG1ZbjFVeTFB
        UzI4cUk4VmlSZW5HZk1FSHdnSEtVRTFYcnc4Cmh3TlA0OTEva1A5cU9vYmYwQjYy
        QXoxWlpFQTlyeVFNQ3RRdk0wTUJLUEEKLS0tIGI4VW13ZHhzTUYxSlRQZUd1c2FE
        ZG5SV1g0Y0ZXd1E3WmNLZGxwRnZDRWMKJZgylviXoMWWZ0SVtCN8Ag1lptmqpjAh
        H2rVzLazKV0YcBDmqS/cNnv2AVhqw2IBXgzI/Ea5IvFMWbp34BpgRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a5cyt62c4ejr28d307x6prc2vrzvhugvelu7eq8vcs0gjmrjvuwq5vnd88
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dWtZTnJUbThIRWxuOGRL
        YVlKczhYUVo1NzdIdS9mRGhDeWY4VnBVNXhnCm80WkJvdEM0emVJU1VoY1NGS0dz
        OTBNblA3WGc1ejQxQmJMb2d4QklXdWsKLS0tIFhzMGRFNS81SFZMa3VOTkJ2VWt3
        WGxMNDZPSmFEVWRFNUZSRHdnSDdOZWMKRMRp4IOXhCq6CSWWH6Fpuvp3Tx+kGFDc
        huXtNweu7WBwsIY3jjOq3SBHUT4jOivNPxN4q6QRD1A0xXW293f7nw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g96vx3ghxfge06xkxrfcfwq607p4fp75xcg6efgz9mf87l2a7u5qk04rfw
  lastmodified: '2026-06-13T15:17:17Z'
  mac: ENC[AES256_GCM,data:Trn/1PWBgVME1V6Z29aSfeYYGtmDdzftrHeZtaxveHlq2yjor0iTQgRfwFXb6C/XNW+GOgGOYn7mB60UEowNpyBrLXx4ZUshxh4KD9RPYdPPZR2WoXtYNj63umDtv955eVCE4pKET+x5HzUiz5H3cOD2dKxptq2Kt9fSKWFOIXY=,iv:HfYRKz4Vc1Gclvi+YczZ1cNSlVm9YCz1SwK3H+FSTYI=,tag:vH0GFFwsFmJj0D7PhMKXWg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
