tailscale-authkey: ENC[AES256_GCM,data:JgoGCIEZxTExLYthPWBCNyIFxrmcElFJzcdkbSLQeRvmr+l2dHkLo7KF/dYgiD7MtzDVTdLjOVOH3rLWGQ==,iv:XO/nZn4qX1NOzHJtf3x88p7/4nMGIhNvCatrpxNa3es=,tag:1sVkg+VDf+5Y4AFxHtPjpw==,type:str]
wifi: ENC[AES256_GCM,data:RTNRGWtC1ZRVOXLfZTJ0cHLgKILfaxbQwfVGdnxTGHfl5HGsDEP5mtqc9SROZh8zFEfDhDGTlKNOO7RxXNBLEVnCxsNBWg==,iv:yM1Y+pofbcMSbilQspLkvRBZ2yizXebnGsBzSayuJWs=,tag:5Zg3nougOdCIBSfMMCuIWw==,type:str]
course-session: ENC[AES256_GCM,data:gwgS07ZC52zLdgIDGIeCVhcZEcE8iHL5eXSph8w609I=,iv:aA3rcy1l4j8PfQgZXzZ/YTtnJCAkUOvggMfO8vFFINY=,tag:lFdVCibEhWIKflTqBG5Rag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZGJndFl1UWx0bUV4T2JE
            WFRkT2V6ZzJFVWVyQjI2WTNjUUd3dFJPS0JVCjVLYVY4c09qMDRTb1Bob1EzK1J5
            V0lVYXFUVXA5UG9jRGEzOEpFbFRpc2cKLS0tIHo3OURmTUNwV21pSVJrazVrOTFJ
            SlRUd2t5Tlkvc29UK25EZTN3UktrcjgKua7adz+gHGtzSf5/1BXIPdl34sKpPubC
            JDRflf94qgm1EitgTGoLs1te6pRYgVmW8+ps+RMrZIouP3+TuZt8xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u8ah2hga53uh7y24efhuc5vszzctqxth2rtvd7dshedpl9l50d5slzs6zq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpKyttMmlXeDM5cTc0SVdM
            M2ZNQlZ2ZlE1L3dJNVhTa1o2YlBrSlFRMzNJCmc3S0lHaWtMalRjekk0WjdjVHdD
            dHFJRFYvakE0R2JMdWp2UmlVMWEyNUUKLS0tIHVEdDNiMmlUL3ZSZ0pZSW1hZmdj
            R3RmeUdBcWJpMnpaNFVRbWRyS05VTkEKjwgnGV9sAR+QyUtFQZxXKwdJ5+4dSgEn
            95Xw0e5aP/W7ZVtk8lNzEKvbzyfuXWJkFnFcphjyL5l7ElSz+zK9MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ahvwx3a7z6df3avdy6w9y3a4ggqvv80s3thqu4dlqj76822ct36qh23jle
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL1VONWx6YTM1T2xsRzhl
            Z1ZRN0JhZk9leW1XN2JOc2k5VmVjRkNCNmtZCkpzSTMxbDhPM3FVWGlaYmVtTjBE
            YjBmV3V3VW1pbVdRQUhWNW5nWlZDeGMKLS0tIE9Kd0ZRQzFDSTd4K0VhcXRpaEtt
            a012K0tJbCtnY3VFN2JzdUZ0RTJGNlUK6kxtoOOuP1Y3Dh6qNfy3Ld3fQdJNoNGK
            tZqa6XQ2EU4RPgk2o/VyYIFDiDSTaJzsW436baMa7EEGZiqfVB+OMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a5cyt62c4ejr28d307x6prc2vrzvhugvelu7eq8vcs0gjmrjvuwq5vnd88
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MkFTcVZEaWNRL0ZsNkwx
            b25zTFRVSWhzeVFVQzlhcXV2by9qUjJPakZJCi91aW9PRlNoSDBsRmJ0dkpYMUF5
            dFMrU2VYWnF1QUJBemJXd2NNZGl2SEkKLS0tIDV4cng1am5wanNSQTRPWmovU0pv
            VmRvUUxJdmUwbXozRHE4L2JyRmJHbUUKrVDpag1A0rOMZkK5e4/C9MjHgjXmI6ee
            DJElyfbjStiXS/lpgGjKHTmYuL/I/OwllxItnUMhQzulA8m+2zHrVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g96vx3ghxfge06xkxrfcfwq607p4fp75xcg6efgz9mf87l2a7u5qk04rfw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRjZPSUI3KzlLOEZFZVJh
            bkNlNmJsemlzdE1MeVNUbmNnUnRpNW5qaWhzCjQ4VmIvVkdWMnorT3BjQVRaby96
            RklhMmJwMWl3L2d5MEVnVTBJZzBDZEEKLS0tIFRuWVpkQmkxbnM5Zit0UTRZK1hv
            SVd5TjAzbElrTWJiL3RjUXpXaUcrNkUKo2Ui9Tqxp37P0BZ9pJtaAUQ/hChnWH00
            wjl5YtnvfYCWJc2HuYrj7/mucrZYJy5VM6XGrrt/W+Yg/bDt87WlMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j4vdcmfjt7ws5fwg4lgskyn0szfn63sj64023ed0u6cp52xzpv4qrrluc2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOVJGalZ0eHQydGpzTmhJ
            UVhmQUxYY2ZhZW12YlJteU4wZW92dU15NmlRCnNaRFhrK3NmRncrb3VyWGZqUkdm
            NnhNNEF5amk2NE5NY0NLMkZ0cHJOMWsKLS0tIHl1OVNkZXVsRXBUckdpVW5sVlhK
            cUxjQTJVUkZkaUpueW1QMEZFT3BvelEKaGFbOl2NEUAK7xa/JBEJPPha790Hr3DG
            Fv5ePqJXMxMBVZrs6oh13JPbYPpMxSuW8HrzpRnPKucyeKZmFh+R2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18vhwvn7ra09rhdc3ex5scd6n96w3lvpv54sa2gvky7559exdhyus6gjmln
    lastmodified: "2026-07-16T05:58:25Z"
    mac: ENC[AES256_GCM,data:XzoBOkG39wO2OyXqJJ+9peNQWhh9rOoafjKKdX6KQk1I8a+dLt1PupFaIukz7ypyq5LQ3FbfqLEi9D1ivFUUJUVksvQAEGUDck/Esf0DTnQ6j06jw7Iu1X4YHWlTA8I7UBzHHcc+61ch5ZvpSuK7ELjdatqCXvBWkrINBgiSPY4=,iv:4/p8a+4XxnLTi9TA7uP2h1bcjzs59FgDOVEnx5xwXBg=,tag:p3eq5vuDH1DUyTWz9g8gaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
